# Generated by Django 4.2 on 2023-04-09 20:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='')),
                ('employee_num', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=150, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommLetter',
            fields=[
                ('letter_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('letter_file', models.FileField(upload_to='')),
                ('letter_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_from', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_received_date', models.DateField()),
                ('letter_noted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_recom_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_agenda', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField()),
                ('event_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('no_participants', models.CharField(blank=True, max_length=100, null=True)),
                ('impl_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('memo_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('memo_date', models.DateField()),
                ('memo_file', models.FileField(upload_to='')),
                ('memo_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('memo_content', models.TextField(blank=True, null=True)),
                ('memo_to', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_to_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_thru', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_thru_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_from', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_from_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_recomm_by', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Moau',
            fields=[
                ('moau_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('moau_file', models.FileField(upload_to='')),
                ('moau_title', models.CharField(blank=True, max_length=255, null=True)),
                ('moau_objective', models.TextField(blank=True, null=True)),
                ('moau_approve_date', models.DateField()),
                ('moau_notarized_by', models.CharField(blank=True, max_length=100, null=True)),
                ('moau_notarized_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('so_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('so_date', models.DateField()),
                ('so_file', models.FileField(upload_to='')),
                ('so_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('so_content', models.TextField(blank=True, null=True)),
                ('so_for', models.CharField(blank=True, choices=[('researcher', 'Researcher'), ('secretariat', 'Secretariat')], max_length=100, null=True)),
                ('so_signedby', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoauSignatories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('moau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moau')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoauParties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('represented_by', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('referred_to_as', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('moau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moau')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAgencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_attended', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
