# Generated by Django 4.2 on 2023-04-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moauparties',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='moausignatories',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='memo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='so_for',
            field=models.CharField(blank=True, choices=[('Researcher', 'Researcher'), ('Secretariat', 'Secretariat')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
