# Generated by Django 4.2 on 2023-04-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_moauparties_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commletter',
            name='letter_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='commletter',
            name='letter_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendance_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='memo_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='moau',
            name='moau_approve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moau',
            name='moau_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='moau',
            name='moau_notarized_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='so_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='so_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
