# Generated by Django 4.2 on 2023-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_commletter_letter_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moau',
            name='moau_type',
            field=models.CharField(blank=True, choices=[('MOA', 'MOA'), ('MOU', 'MOU')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='so_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
